### ISSUE TITLE
Could not find the certificate

### ISSUE THREAD

**Issue by djraval** [mscifo/pressless#2]
ACM Certificate region defaults to "us-east-1", rather it can be directly extracted from AWS CLi variables.

Quick Fix to "Certificate not Found" was to add the certificate for the domain to US-EAST-1.

**Comment by mscifo** [comment]
Pressless currently uses https://github.com/amplify-education/serverless-domain-manager for creating the AWS APIG custom domain.  The version we are currently using was released before it was possible to specify the endpoint type of `regional` for an APIG custom domain.  The default value, before and after, is `edge`.  The default `edge` endpoint type "require that the certificate be located in us-east-1 to be used with the CloudFront distribution.".  The `edge`-optimized API endpoint is the only endpoint type currently supported by Pressless, since `regional` API endpoints are really meant to only be accessed from within the same region or via a custom Cloudfront distribution managed outside of API Gateway. 

You can read more about this at:
https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-regional-api-endpoints/
https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains-prerequisites.html
